apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hourly-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: task-container
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo "Job executed"
          restartPolicy: OnFailure
