apiVersion: batch/v1
kind: Job
metadata:
  name: php-job
spec:
  template:
    spec:
      containers:
        - name: php
          image: php:7.4
          command:
            - "curl"
            - "http://example.com/file.php"
      restartPolicy: Never